elifesciences/elife-spectrum

spectrum/checks.py, spectrum/input.py, spectrum/test_article.py
Checking the images also on `elife-published`. Checking the XML on there, too. Maybe I'll add also the PDF?
=> S3 checks for elife-published

requirements.txt, spectrum/input.py, spectrum/test_api.py, spectrum/test_article.py, spectrum/test_journal.py, spectrum/test_journal_cms.py
Testing then not only the Journal CMS interface works but also the integration with bus and search picking message of that.
=> Adding content to Journal CMS and testing for it

checkout.sh, conftest.py, spectrum/checks.py, spectrum/generator.py, spectrum/templates/elife-15893-vor-r1/elife-15893.xml.jinja, spectrum/test_article.py
- Checking relatedness of articles on Lax
- (commented out) results of the /recommendations API
=> Related articles and recommendations testing expansion

spectrum/checks.py, spectrum/test_journal.py
- Various semi-static pages
- Consistent testing of all known listings
- Parameterizing tests for independence
=> Testing remaining Journal pages

README.md, spectrum/checks.py, spectrum/test_article.py
EIF is going to be deprecated and the dashboard can tell a lot more about what is happening
=> Using DashboardCheck before EIF

load_journal.py, spectrum/checks.py
- Renaming exceptions to standard Error suffix
- Logging exceptions rather than failing fast
- Improving error message on UnicodeDecodeError
=> Various load testing feedback

spectrum/checks.py, spectrum/test_api.py
This is the endgame, but interim updates may be necessary like commenting out the test on the journal page.
=> Renaming to labs posts

spectrum/test_article.py
And as the first item. Looks like this is finally working?
=> Testing two related articles recommend each other

spectrum/checks.py, spectrum/test_article.py
Currently failing, as invalidation isn't working.
=> Invalidation checks

load-small.sh, load.py, spectrum/checks.py, spectrum/load.py
- introducing `spectrum.checks.ReviewerSuggestionsCheck`
- introducing `spectrum.load.ReviewerSuggestions`
- `load.py` is now generic
=> Load testing reviewer-suggestions

spectrum/templates/elife-00666-vor-r1/elife-00666.xml.jinja
I have run http://ci--alfred.elifesciences.org/job/dependencies-elife-spectrum-update-kitchen-sinks-github/142/ which resulted in this pull request.
=> Updated kitchen sinks from Github (elife-00777.xml,elife-00666.xml)

requirements.txt, spectrum/checks.py, spectrum/test_article.py
Depends on a few other PRs to become green, see ticket.
=> ELPP-3356 Published articles in RSS feed

spectrum/aws.py, spectrum/checks.py, spectrum/input.py, spectrum/test_article.py
We are not able to cleanly start the workflow yet, but the test:
- cleans the outbox
- publishes an article
- check the article is in the outbox
Later on, it will:
- start the right workflow
- check the article is moved to the published folder of the packaging bucket
=> ELPP-3360 Pubmed basic outbox check

spectrum/checks.py
Getting more information out of these errors:
```
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='end2end--ppp-dash.elifesciences.org', port=443): Max retries exceeded with url: /api/article/1225690203723615893 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f71afb297d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))",)
```
=> Attempt to log ip after ConnectionError exceptions

spectrum/checks.py, spectrum/test_api.py, spectrum/test_article.py
Any profile id should do once https://github.com/elifesciences/hypothesis-dummy/pull/2 is in place always providing some fake annotations.
=> ELPP-3366 Access annotations list for a profile

spectrum/test_journal.py
- profiles ids are dynamically generated, only ORCID dummy data is constant
- the order with which tests are executed is not specified, so the profile existence has to be ensured before it can be loaded
=> Comply to dynamic profile ids

spectrum/input.py, spectrum/test_article.py
As it stands uploading the bucket should trigger the notification automatically, and start the workflow without an explicit command.
=> ELPP-1266 Automated silent corrections

spectrum/checks.py
A race condition from https://elifesciences.atlassian.net/browse/ELPP-3665?focusedCommentId=32085&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-32085
Actually a bug in the dashboard, but easier to work around.
=> ELPP-3665 Continue polling if no preview-link exists on dashboard

conftest.py, requirements.txt, spectrum/checks.py, spectrum/debug.py, spectrum/exceptions.py, spectrum/generator.py, spectrum/input.py, spectrum/test_article.py
This isn't support to work yet, but it helps documenting the process.
When running the test, I get as far as uploading the files to S3 and send a message with `econtools`:
```
2018-07-02T15:42:10Z INFO queue_workflow_starter_1659 1 message received
2018-07-02T15:42:10Z INFO queue_workflow_starter_1659 message contents: <boto.sqs.message.Message object at 0x7f1fb4c52390>
```
but then no workflow starts, we know some compatibility has to be tuned there.
=> ELPP-1599 Cover PackagePOA

spectrum/test_api.py
Depends on https://github.com/elifesciences/digests/pull/15 for content negotiation.
=> Simple API check for /digests

conftest.py, spectrum/articles.py, spectrum/checks.py, spectrum/generator.py, spectrum/test_article.py, spectrum/test_digest.py
For https://github.com/elifesciences/issues/issues/4326
This test may "pass" at the moment, but only because we don't do any check after ingesting this article.
=> Ingest an article with a digest

README.md
For https://github.com/elifesciences/issues/issues/4435
=> Document how to run tests from your laptop

conftest.py, install.sh, requirements.txt, spectrum/checks.py, spectrum/config.py, spectrum/exceptions.py, spectrum/generator.py, spectrum/import.py, spectrum/input.py, spectrum/load.py, spectrum/polling.py, spectrum/test_article.py, spectrum/test_journal.py
=> Upgrade to Python 3

spectrum/config.py
They happen only in some contexts, and these are all testing environments
=> Try to disable urllib3 warnings on HTTPS

conftest.py, reset-build.sh, spectrum/input.py, spectrum/test_xpub.py, spectrum/xpub.py
- Separate a new test for covering the start of the initial submission process
- Go through the dashboard to get to the first page, author-related
- Compile the first page of the process
- Take final screenshots of all Selenium tests
=> Xpub initial submission: compile first page

.pylintrc, spectrum/test_xpub.py, spectrum/xpub.py
Gets to the point of selecting senior and reviewing editors, integrating `api-gateway` and `journal-cms` test data.
=> Submission and (part of) Editors page

spectrum/checks.py, spectrum/retries.py
For https://github.com/elifesciences/issues/issues/4475#issuecomment-444017091
=> Treat 502 as 504: retry

spectrum/test_xpub.py, spectrum/xpub.py
First step of https://github.com/elifesciences/elife-xpub/issues/1171 is to get to a point in which the upload to EJP is performed.
=> Complete initial submission

spectrum/checks.py, spectrum/generator.py, spectrum/test_xpub.py, spectrum/xpub.py
Completes https://github.com/elifesciences/elife-xpub/issues/1171
We retrieve the MECA files that have been uploaded recently, unzip `article.xml` in each of them and build a list of titles. Our title must be in the list.
Depends on https://github.com/elifesciences/builder-base-formula/pull/200
=> Check xpub MECA uploads titles

spectrum/input.py
Done as a result of the page titles having now been changed.
See:
- https://github.com/elifesciences/elife-xpub/issues/1586
- https://github.com/elifesciences/elife-xpub/issues/1617
=> update expected title for selenium_title_smoke_test

requirements.txt
Just got an email about this being a security issue
=> security fix

requirements.txt
See https://github.com/elifesciences/issues/issues/4874
=> Upgrade Jinja2 to 2.10.1

requirements.txt
=> Fix: bumps urllib3 for CVE-2019-11324

spectrum/test_xpub.py, spectrum/xpub.py
For https://github.com/elifesciences/elife-xpub/issues/1984
=> Update tests to go through `Before you start` page

install.sh
=> install.sh, removes python minor version

.pylintrc, install.sh, requirements.txt
Fiddled on `elife-libraries--spectrum` to make the simplest possible test work.
=> Allow Python 3.6

spectrum/templates/elife-04177-vor-r1/elife-04177.xml.jinja
this fixes a broken path to an image
=> xml fixture, renames a MSA from 'Immunology' to 'immunology-inflammation'.

spectrum/templates/elife-00777-vor-r1/elife-00777.xml.jinja
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-elife-spectrum-update-kitchen-sinks-github/980/display/redirect which resulted in this pull request.
=> Updated kitchen sinks from Github (elife-00777.xml,elife-1234567890.xml)

example-local-test.sh, spectrum/test_article.py
it's not playing well with others but appears to work ok in isolation. 
still trying to pin down reason.
- https://github.com/elifesciences/issues/issues/7719
=> test_article, disabling test_adding_article_fragment temporarily.

spectrum/checks.py
related to pubpub reverse proxy
=> Don't check about pages on journal for the moment

spectrum/checks.py
This is to accommodate the following change in journal code: https://github.com/elifesciences/journal/pull/1804/files
=> Allow Publication history or Version history as title of version history
