elifesciences/elife-spectrum

.pylintrc, conftest.py, spectrum/checks.py, spectrum/generator.py, spectrum/input.py, spectrum/test_article.py
The new test performs:
- ingest of a `*-r1.zip` file. This causes an `ingest` command from bot to lax.
- ingest of a `*-r2.zip` with the same article and an modification in the text. This causes another `ingest` command from bot to lax.
- publishing the run resulting from `*-r2.zip`. This causes a `publish` command from bot to lax.
- verifying the edit of `*-r2.zip` is visible through Lax's API.
However, this already passes so it does not reproduce https://github.com/elifesciences/lax/pull/54 because that problem is not fixed on the `develop` branch.
@lsh-0 any pointers on how to reproduce that particular problem?
=> Multiple ingests

spectrum/checks.py, spectrum/test_article.py
Publish an article that contains an invented word, poll until it is available through the API, check that Journal search page can see it. The scope is always testing the protocol integration, not details on how the page displays the results.
=> Added assertion that counts element in Journal's search page

spectrum/checks.py, spectrum/test_article.py
Would be better if we publish two articles, and one recommends the other. However, this tests will be running in parallel with many others so it cannot rely on "recommend the latest" rules.
Which rules could be used to have a deterministic result like:
- I publish 1
- I publish 2
- no matter what else is happening around, 2 recommends 1 (or at least it recommends 1 plus other stuff)
?
=> Expanding test to also check Journal article page

spectrum/input.py, spectrum/test_article.py, spectrum/test_journal_cms.py
- New schema in IIIF of blog articles
- Updated other journal-cms image check to target IIIF, foreseeing it will  break
- Failing fast on article fragments: if form doesn't load, stop the test
One of the two failing tests passes, while the other tries to load `/admin/structure/article_fragment/add` and gets a 500 saying
```
The website encountered an unexpected error. Please try again later.
```
The PHP error log shows:
```
[13-Apr-2017 08:03:18 UTC] Uncaught PHP Exception Drupal\Component\Plugin\Exception\PluginNotFoundException: "The "" entity type does not exist." at /ext/srv/journal-cms/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php line 133
```
when that happens.
/cc @nlisgo
=> Journal CMS new Drupal and IIIF changes

conftest.py, load_journal.py, spectrum/checks.py, spectrum/input.py, spectrum/load.py, spectrum/logger.py, spectrum/test_journal.py
Single process, which can be executed in multiple copies.
Chooses between three kind of loads to create:
- loading a static page
- going through a listing's item and pages
- searching for a random string
When a page is visited, all resources like scripts, CSS and images are accessed (through HEAD requests at the moment).
To be expanded with other pages or workflows we are interested in for stress testing.
=> Load testing Journal

checkout.sh, import-xml.sh
- Error in xmllint should propagate up and make the update build fail
- Local modifications should be overwritten when checking out master or any branch
We had a kitchen sink that wasn't valid in https://ci--alfred.elifesciences.org/job/dependencies-elife-spectrum-update-kitchen-sinks-github/36/console, then it remained there and was passed to the bot as an empty file.
=> Robustness in kitchen sink update

spectrum/checks.py, spectrum/input.py, spectrum/test_article.py
Or to any backend, for that matter. The test uses an invented, unique word to
reliably find one item in the search API:
```
[2017-05-22 15:02:18,948][INFO][spectrum.checks][4348358295504415893]
Found article version 1 on api:
https://end2end--gateway.elifesciences.org/articles/4348358295504415893
[2017-05-22 15:02:19,862][INFO][spectrum.checks][] Found
https://end2end--cdn-iiif.elifesciences.org/journal-cms:article/2017-05/king_county_158.jpg/full/full/0/default.jpg:
200
[2017-05-22 15:02:20,687][INFO][spectrum.checks][]
https://end2end--gateway.elifesciences.org/search?for=g5odqr1seqg5spobyml4jeouzn0aay:
returning 1 results and satisfying check
SearchItemCheckImage(https://end2end--cdn-iiif.elifesciences.org/journal-cms:article/2017-05/king_county_158.jpg/full/full/0/default.jpg)
```
=> Checking propagation of article image update to search

spectrum/checks.py, spectrum/input.py, spectrum/test_article.py
Solves some instabilities such as https://ci--alfred.elifesciences.org/job/test-journal/886/console
After adding the article fragment, better to wait for an image field to
appear in the article on the API. Then we can check its propagation to
search and even check its URI, since we now have that value. No easy way to
predict the URL from journal-cms
=> Checking an image field appears in the API first

spectrum/checks.py, spectrum/test_article.py
spectrum tests now use lax api v2 rather than v1. v1 api has been removed.
@giorgiosironi , this is a pretty naive edit but if you're happy with it, could you merge it and give this run a kick? https://ci--alfred.elifesciences.org/blue/organizations/jenkins/test-lax/activity
cheers
=> Feat lax article check api v2

spectrum/checks.py
We load many resources in parallel taken from the page HTML code. However if we get a 504 from CloudFront we can retry rather than failing.
The retry is not parallel, it's supposed to happen rarely
=> Retry on 504 on page resource

spectrum/checks.py, spectrum/test_article.py
After an article has been published, we should have two personalised covers available and publicly accessible in the related bucket. We can predict their name and poll for their existence.
=> Test personalised covers

spectrum/input.py, spectrum/test_journal.py
Journal tries to log in, uses profiles and the orcid-dummy to do so. We don't have control on what happens on the ORCID side, so orcid-dummy sends back the user with a successful authentication without any further user interaction.
The only check we can make on the logged in page so far is on the `Log out` button. We don't log out as it's not an integrated feature (so far), that can be tested purely in journal.
=> Connecting journal and profiles

spectrum/checks.py, spectrum/test_api.py, spectrum/test_journal.py
Very rough at this time.
- Load /profiles as a sanity check
- Adding check on profile sanity after login
=> Basic end2end tests involving /profiles

spectrum/input.py
There now isn't a log out link in the site header (without JS), instead there's a link to the profile page where it's found.
=> Update Journal profile and log out links

spectrum/input.py, spectrum/test_journal.py
Turns out the existing test already loads the logged in user's own profile page.
The test being added loads the same page from the point of view of an anonymous user, considering its public version which may differ and feature less content.
The anonymous user still enables its feature flag.
=> ELPP-3366 Check a public profile page

spectrum/checks.py
https://alfred.elifesciences.org/job/test-lax/589/console failed because the test article (having an old date probably) was not in the first 100. It's a slowdown to check all pages in every polling round, but the article may be anywhere.
Observer is cleaned daily https://alfred.elifesciences.org/job/process-clean-end2end/ so that pages do not accumulate.
=> Access observer using pagination

spectrum/checks.py
The dashboard API only returns a timestamp in seconds, so we cannot strictly compare with a microsecond timestamp generated by the tests. Ensure both are seconds and compare with `>=`.
=> Filter with run_after using greater than or equal

spectrum/input.py, spectrum/test_journal.py
```
spectrum/test_journal.py [2018-01-30 14:00:32,818][INFO][spectrum.input][] Visiting https://end2end--journal.elifesciences.org/about
[2018-01-30 14:00:33,044][INFO][spectrum.input][] Logging in at https://end2end--journal.elifesciences.org/log-in (headers {'Referer': 'https://end2end--journal.elifesciences.org/about'})
[2018-01-30 14:00:34,931][INFO][spectrum.input][] Redirected to https://end2end--journal.elifesciences.org/about after log in
[2018-01-30 14:00:34,933][INFO][spectrum.input][] Found logged-in profile button at .login-control__non_js_control_link
[2018-01-30 14:00:34,933][INFO][spectrum.input][] Logging out at https://end2end--journal.elifesciences.org/log-out
[2018-01-30 14:00:35,412][INFO][spectrum.input][] Redirected to https://end2end--journal.elifesciences.org/ …
```
=> Full log in and log out scenario

spectrum/input.py, spectrum/test_journal.py
Even when we'll use flags for other features, it's likely to be implemented on a per-user basis rather than with a query string.
=> Remove feature flag

spectrum/input.py
Other tests are more robust and are able to dynamically choose the right button, but this one needed to anchor on a text. Can be refactored but on a green end2end, not while it is red.
/cc @nlisgo
The build of this should run over the rolled-forward journal-cms, with the updated Drupal.
=> Change button label of blog article form

requirements.txt, spectrum/checks.py
Trying to use the generic `backoff` library since not all backoffs are done through `requests` (e.g. `boto` for S3 access), this could potentially substitute `polling` for other checks too (later on).
=> ELPP-3447 Exponential backoff on 504 responses

spectrum/generator.py, spectrum/input.py, spectrum/test_article.py
I am using the article `elife-15893-v1` as a template.
The configuration file uploaded to `end2end-elife-bot` has:
```
$ cat article_subjects.csv 
DOI,subj-group-type,subject
10.7554/eLife.32656,heading,Biochemistry and Chemical Biology
```
but the subjects do not get rewritten:
```
curl -s https://end2end--gateway.elifesciences.org/articles/134820053256315893 | jq .subjects
[
{
"name": "Biochemistry",
"id": "biochemistry"
},
{
"name": "Biophysics and Structural Biology",
"id": "biophysics-structural-biology"
}
]
```
`worker.log` says:
```
2018-02-16T16:16:59Z INFO worker_1394 activityType: ModifyArticleSubjects
...
2018-02-16T16:16:59Z INFO worker_1394 did not modify any article subjects in the article xml
```
(the test is missing the assertion for now, I was doing the check manually)
=> ELPP-3445 Change subject of an article through silent correction

spectrum/checks.py
We now have ones like `1.3x` (https://github.com/elifesciences/journal/pull/763).
=> Allow for decimal srcset descriptors

spectrum/checks.py, spectrum/test_article.py
Avoids the redirect. (That should be tested individually if it's considered important.)
=> Update Journal article URI

spectrum/input.py, spectrum/test_journal.py
Sample logs
```
spectrum/test_journal.py [2018-06-13 10:46:00,454][INFO][spectrum.input][] Logging in at https://end2end--cdn-journal.elifesciences.org/log
-in (headers {})
[2018-06-13 10:46:04,124][INFO][spectrum.input][] Redirected to https://end2end--cdn-journal.elifesciences.org/ after log in
[2018-06-13 10:46:04,125][INFO][spectrum.input][] Found logged-in profile button at .login-control__non_js_control_link
[2018-06-13 10:46:04,673][INFO][spectrum.checks][] Found https://end2end--gateway.elifesciences.org/profiles: 200
[2018-06-13 10:46:04,674][INFO][spectrum.input][] Loading page /profiles/yvc20pqz
.
===================== 1 passed in 6.52 seconds ======================
```
This hits CloudFront at the moment, it will hit Fastly after porting.
=> ELPP-3393 Add test to log in through journal's CDN

spectrum/checks.py
```
[2018-08-02 17:20:37,352][INFO][spectrum.checks][1777256512047515893] Found https://end2end--ppp-dash.elifesciences.org/api/article/1777256512047515893 version 1 in status ready to publish on dashboard with run b3d50b2e-c1bf-4c4d-83ac-2bff6cefab48 (required: events: ['Ready To Publish'])
```
Caused https://alfred.elifesciences.org/job/test-journal/1542/
=> Check also events of a run before believing `ready to publish`

Jenkinsfile
4 builds started, if my calculations are correct a new one superceding the older ones should make those abort (saving time albeit losing the result of intermediate commits).
=> Try milestone step to abort old builds

spectrum/articles.py, spectrum/checks.py, spectrum/test_article.py, spectrum/test_digest.py
For https://github.com/elifesciences/issues/issues/4462
- Enable check on digest published image (unrelated)
- Add silent correction of an article with a digest
- Add check for digest text modification coming from article
=> Test digests on silent corrections

spectrum/mailcatcher.py, spectrum/polling.py
Tuples are used internally to pair together a `(result, details)` while polling, but if no errors are encountered only `result` is exposed.
=> Correctly expect only a result when polling for mail messages

spectrum/input.py, spectrum/test_journal.py, spectrum/test_xpub.py
Also getting closer to the behavior of https://github.com/elifesciences/builder/pull/430 which needs the CDN to appear.
=> Use journal's CDN when testing integration with xpub

spectrum/input.py
This was removed because of backward compatibility issues.
See #162
=> Reinstate the test for the title

spectrum/checks.py, spectrum/test_api.py, spectrum/test_journal.py
Part of https://github.com/elifesciences/issues/issues/4291 but spawned because `medium--end2end` was discovered as being broken as part of https://github.com/elifesciences/issues/issues/4558.
=> Remove medium service tests

spectrum/xpub.py
For https://github.com/elifesciences/elife-xpub/issues/1709
Manually switching `elife-xpub--end2end` to the `develop` version (currently failing) gives:
```
[2019-03-20 09:42:06,261][INFO][spectrum.xpub][elife-xpub] Found cookie notice button button[data-test-id="cookieAcceptButton"] `GOT IT`
[2019-03-20 09:42:06,304][INFO][spectrum.xpub][elife-xpub] Clicked cookie notice button button[data-test-id="cookieAcceptButton"]
[2019-03-20 09:42:06,304][DEBUG][spectrum.xpub][] Cookie notice visibility check
[2019-03-20 09:42:16,368][DEBUG][spectrum.xpub][] Cookie notice buttons: 0
```
=> Dismiss cookie notice on xpub during login process

spectrum/templates/elife-15893-vor-r1/elife-15893.xml.jinja
For https://github.com/elifesciences/issues/issues/4858
The article has been modified during its history to map it to new subjects. One old subject doesn't exist anymore in `personalised-covers`, hence we need the latest version to be able to run it through the publication pipeline.
=> Update elife-15893 template with current subjects

spectrum/xpub.py
https://alfred.elifesciences.org/job/test-elife-xpub/909/artifact/spectrum.test_xpub.test_initial_submission-2019-04-24T10%3A51%3A23.096623.png seems to have failed on a minimum 60-word count being required. This brings us to ~75 words.
=> Increase cover letter word count

spectrum/checks.py
https://alfred.elifesciences.org/job/test-journal/1817/ (https://github.com/elifesciences/journal/pull/1243) failed as some of the Journal paths have changed and https://github.com/elifesciences/journal-formula/pull/114 hasn't been merged yet.
=> Update Journal paths

spectrum/test_article.py
`elife-bot` pipeline build https://alfred.elifesciences.org/job/test-elife-bot/920/ has one failure, which I think is directly related to the code changes to the PubMed deposit workflow I merged in.
I think this is one that does happend to have end2end tests, described on issue https://github.com/elifesciences/issues/issues/4053 a couple years ago some FTP capability was added in to check the PubMed workflow.
With the switch to SFTP, end2end will be unable to complete the workflow successful, and it will not find the resulting batch file in the published folder of the S3 bucket.
I seem to remember end2end did not have SSH/SFTP/SCP capability, which is mentioned briefly in comment https://github.com/elifesciences/issues/issues/4053#issuecomment-402123490
Considering how adding an SFTP …
=> Temporarily Disable check for PubMed deposit.

spectrum/input.py
See: https://github.com/elifesciences/journal-cms/pull/620
This change will allow the test to work before and after the `inline_entity_form` update. The test coverage remains the same and once the above PR is merged and deployed I will create a followup PR to remove the condition.
=> create_podcast_episode breaks when inline_entity_form is updated

example-local-test.sh, spectrum/test_api.py, spectrum/test_journal.py
orcid's referer redirect behaviour has changed.
=> journal, disables tests that require logging in through orcid.

spectrum/templates/elife-00625-vor-r1/elife-00625.xml.jinja
Re issue https://github.com/elifesciences/issues/issues/6586
This should fix the personalised covers generation bug related to an old Major Subject Area (MSA) value in an article XML template file.
=> Corrected MSA Developmental Biology in 00625.

spectrum/templates/elife-00230-vor-r1/elife-00230.xml.jinja, spectrum/templates/elife-01222-vor-r1/elife-01222.xml.jinja, spectrum/templates/elife-03318-vor-r1/elife-03318.xml.jinja, spectrum/templates/elife-04637-poa-r1/elife-04637.xml.jinja, spectrum/templates/elife-04970-vor-r1/elife-04970.xml.jinja, spectrum/templates/elife-08245-vor-r1/elife-08245.xml.jinja
Re issue https://github.com/elifesciences/issues/issues/6586
These are some additional `<subject>` values in XML templates which may be out-of-date, and I changed them to reflect the tagging in the currently published articles.
=> MSA updates, biochem, genomics, biophysics

spectrum/test_article.py
In PR https://github.com/elifesciences/elife-spectrum/pull/269, an XML template used in testing was updated to have the subject value `Immunology and Inflammation` for compatibility with the personalised covers generation.
The test scenario changed in this PR also uses the `Immunology and Inflammation` value when it tests rewriting the `<subejct>` tags of the XML.
=> Use Immunology and Inflammation in subject rewrite

spectrum/checks.py, spectrum/retries.py
I intend for this to be temporary until the root cause of the problem is found. In the interim this *may* allow some time-expensive tests to pass where they would otherwise have failed.
=> retries.py, adds 404 as a case that should be retried.

spectrum/checks.py, spectrum/generator.py, spectrum/test_article.py
Improves: https://github.com/elifesciences/issues/issues/7433
The check that I'm removing was not working as intended. It should be re-introduced but as the main goal of the check wasn't being executed I was happy to remove it as the less valuable check to see that the figures url was present is already covered in the `journal` application tests and need not be a focus of end2end.
The more valuable check of ensuring that all of the assets load correctly on the figures page should be introduced and I will submit a followup PR to start us off on this. The current test failed to perform this check which is why I was happy to remove the code.
The following line of code should be `self.generic(figures_url)` rather than `self.generic(url)`: …
=> Remove article has_figures flag as test broken and currently blocking deployments
